Trigger redeployment

diff --git a/.github/workflows/azure-static-web-apps-victorious-bush-0c1f7fb03.yml b/.github/workflows/azure-static-web-apps-victorious-bush-0c1f7fb03.yml
--- a/.github/workflows/azure-static-web-apps-victorious-bush-0c1f7fb03.yml
+++ b/.github/workflows/azure-static-web-apps-victorious-bush-0c1f7fb03.yml
@@ -27,15 +27,20 @@ jobs:
           api_location: ""
           skip_api_build: true
     
-  checking_secret::    
+check_secret_presence:
     runs-on: ubuntu-latest
-    name: Checking secret
+    name: Check Secret Presence
     steps:
-      - name: Checking secret
-        id: closepullrequest
-        uses: Azure/static-web-apps-deploy@v1        
-        run: echo "SECRET: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_VICTORIOUS_BUSH_0C1F7FB03 }}"
-    
+      - name: Check secret length
+        run: |
+          # Use a length check to confirm the secret exists
+          SECRET_VALUE="${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_VICTORIOUS_BUSH_0C1F7FB03 }}"
+          if [[ -z "$SECRET_VALUE" ]]; then
+            echo "::error::Secret is empty or not found!"
+            exit 1
+          else
+            echo "Secret is present. Length: ${#SECRET_VALUE}"
+          fi    
     
   close_pull_request_job:
     if: github.event_name == 'pull_request' && github.event.action == 'closed'
